const menu_list=[
  {
     link:"/auth/home",
     label:"首页",
     icon:"home",
     auth_path:"/",
  },{
    label:"权限管理",
    icon:"key",
    auth_path:"/auth",
    sub_menu:[
      {
        link:"/auth/list-role",
        auth_path:"/auth/role/list",
        label:"菜单权限",
        icon:"security-scan"
      },{
        link:"/auth/list-data",
        auth_path:"/auth/data/list",
        label:"数据权限",
        icon:"security-scan"
      },{
        link:"/auth/list-admin",
        auth_path:"/auth/admin/list",
        label:"人员管理",
        icon:"user"
      }
    ]
  },{
    label:"网站管理",
    icon:"desktop",
    auth_path:"/website",
    sub_menu:[
      {
        link:"/website/setting",
        auth_path:"/website/setting",
        label:"网站设置",
        icon:"file"
      },{
        link:"/website/list-banner",
        auth_path:"/website/banner/list",
        label:"banner管理",
        icon:"camera"
      },{
        link:"/website/list-notice-type",
        auth_path:"/website/notice-type/list",
        label:"公告字典",
        icon:"pie-chart"
      },{
        link:"/website/list-notice",
        auth_path:"/website/notice/list",
        label:"公告管理",
        icon:"file"
      },{
        link:"/website/list-produce",
        auth_path:"/website/produce/list",
        label:"产品管理",
        icon:"file"
      },{
        link:"/website/list-news",
        auth_path:"/website/news/list",
        label:"新闻管理",
        icon:"file"
      },{
        link:"/website/list-partner",
        auth_path:"/website/partner/list",
        label:"合作伙伴",
        icon:"file"
      }
    ]
 },{
  label:"博客管理",
  icon:"tool",
  auth_path:"/blog",
  sub_menu:[
    {
      link:"/blog/list-article",
      auth_path:"/blog/article/list",
      label:"博文管理",
      icon:"pie-chart"
    },{
      link:"/blog/list-type",
      auth_path:"/blog/type/list",
      label:"类型管理",
      icon:"pie-chart"
    }
  ]
},{
  label:"开发管理",
  icon:"tool",
  auth_path:"/develop",
  sub_menu:[
    {
      link:"/develop/list-sql",
      auth_path:"/develop/sql/list",
      label:"SQL监控",
      icon:"pie-chart"
    },{
      link:"/develop/list-swagger",
      auth_path:"/develop/swagger/list",
      label:"API文档",
      icon:"pie-chart"
    },{
      link:"/develop/list-deploy",
      auth_path:"/develop/deploy/list",
      label:"配置中心",
      icon:"pie-chart"
    }
  ]
}
]

export default menu_list;