spring:
  config:
    import:
      - classpath:/config/dev/important.properties
      - classpath:/config/dev/common.properties
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  config: classpath:config/dev/logback.xml